<a href="https://colab.research.google.com/github/Mjoshi543/ML-LAB-102217262/blob/main/ML_Assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Q1: Questions on Basic NumPy Array

a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])

In [ ]:
import numpy as np

In [ ]:

arr=np.array([1,2,3,4,5,6])
print(arr)
print(np.flip(arr))

[1 2 3 4 5 6]
[6 5 4 3 2 1]


b)Flatten the NumPy arr: array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]]) using any two NumPy in-built methods


In [ ]:
arr1=np.array([[1,2,3],[2,4,5],[1,2,3]])
print(arr1.flatten())
print(np.ravel(arr1))

[1 2 3 2 4 5 1 2 3]
[1 2 3 2 4 5 1 2 3]


(c) Compare the following numpy arrays:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])


In [ ]:
arr2=np.array([[1,2],[3,4]])
arr3=np.array([[1,2],[3,4]])
comparision=arr2==arr3
equal_arrays=comparision.all()
print(equal_arrays)

True


(d) Find the most frequent value and their indice(s) in the following arrays:
i. x = np.array([1,2,3,4,5,1,2,1,1,1])
ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [ ]:
x=np.array([1,2,3,4,5,1,2,1,1,1])
print(x)
a=np.bincount(x).argmax()
print(a)
print(np.where(x==a))

y=np.array([1,1,1,2,3,4,2,4,3,3])
b=np.bincount(y).argmax()
print(y)
print(b)
print(np.where(y==b))


[1 2 3 4 5 1 2 1 1 1]
1
(array([0, 5, 7, 8, 9]),)
[1 1 1 2 3 4 2 4 3 3]
1
(array([0, 1, 2]),)


(e) For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'), find
i. Sum of all elements
ii. Sum of all elements row-wise
iii. Sum of all elements column-wise

In [ ]:
gfg=np.matrix('[4,1,9;12,3,1;4,5,6]')
print(np.sum(gfg))


print(np.sum(gfg, axis=0))


print(np.sum(gfg, axis=1))

45
[[20  9 16]]
[[14]
 [16]
 [15]]


(f) For the matrix: n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]]), find
i. Sum of diagonal elements
ii. Eigen values of matrix
iii. Eigen vectors of matrix
iv. Inverse of matrix
v. Determinant of matrix


In [ ]:
n_array=np.array([[55,25,15],[30,44,2],[11,45,77]])
print(np.trace(n_array))
#or
print(np.sum(np.diagonal(n_array)))
#Eigen values and eigen vectors
w,v=np.linalg.eig(n_array)
print("Eigen Values=\n", w)
print("Eigen Vectors=\n", v)
print("\n")
#inverse
print(np.linalg.inv(n_array))
print("\n")
#Determinant
print(np.linalg.det(n_array))

176
176
Eigen Values=
 [98.16835147 28.097044   49.73460452]
Eigen Vectors=
 [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]


[[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]


137180.0000000001


(g) Multiply the following matrices and also find covariance between matrices using NumPy:
i. p = [[1, 2], [2, 3]]
q = [[4, 5], [6, 7]]
ii. p = [[1, 2], [2, 3], [4, 5]]
q = [[4, 5, 1], [6, 7, 2]]


In [ ]:
p=np.array([[1,2],[3,4]])
q=np.array([[5,6],[7,8]])
c=np.dot(p,q)
print(c)
print(np.cov(p,q))
print("\n")

p1=np.array([[1,2],[2,3],[4,5]])
q1=np.array([[4,5,1],[6,7,2]])
c1=np.dot(p1,q1)
print(c1)
print(np.cov(c1))


[[19 22]
 [43 50]]
[[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]


[[16 19  5]
 [26 31  8]
 [46 55 14]]
[[ 54.33333333  89.16666667 158.83333333]
 [ 89.16666667 146.33333333 260.66666667]
 [158.83333333 260.66666667 464.33333333]]


(h) For the matrices: x = np.array([[2, 3, 4], [3, 2, 9]]); y = np.array([[1, 5, 0], [5, 10, 3]]),
find inner, outer and cartesian product?


In [ ]:
x=np.array([[2,3,4],[3,2,9]])
y=np.array([[1,5,0],[5,10,3]])
print("\n")
print(np.inner(x,y))
print("\n")
print(np.outer(x,y))
print("\n")
p=x.flatten()
q=y.flatten()
result = np.transpose([np.tile(p, len(q)), np.repeat(q, len(p))])
print(result)




[[17 52]
 [13 62]]


[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]


[[ 2  1]
 [ 3  1]
 [ 4  1]
 [ 3  1]
 [ 2  1]
 [ 9  1]
 [ 2  5]
 [ 3  5]
 [ 4  5]
 [ 3  5]
 [ 2  5]
 [ 9  5]
 [ 2  0]
 [ 3  0]
 [ 4  0]
 [ 3  0]
 [ 2  0]
 [ 9  0]
 [ 2  5]
 [ 3  5]
 [ 4  5]
 [ 3  5]
 [ 2  5]
 [ 9  5]
 [ 2 10]
 [ 3 10]
 [ 4 10]
 [ 3 10]
 [ 2 10]
 [ 9 10]
 [ 2  3]
 [ 3  3]
 [ 4  3]
 [ 3  3]
 [ 2  3]
 [ 9  3]]


## Q2: Based on NumPy Mathematics and Statistics


(a) For the array: array = np.array([[1, -2, 3],[-4, 5, -6]])
i. Find element-wise absolute value
ii. Find the 25th, 50th, and 75th percentile of flattened array, for each column, for each
row.
iii. Mean, Median and Standard Deviation of flattened array, of each column, and
each row

In [ ]:
array = np.array([[1, -2, 3], [-4, 5, -6]])

# (i) Element-wise absolute value
abs_array = np.abs(array)
print("Element-wise absolute value:")
print(abs_array)

# Flattened array
flattened_array = array.flatten()

# (ii) Percentiles
percentiles_flattened = {
    '25th': np.percentile(flattened_array, 25),
    '50th (Median)': np.percentile(flattened_array, 50),
    '75th': np.percentile(flattened_array, 75)
}
print("Percentiles of flattened array:")
print(percentiles_flattened)

percentiles_columns = {
    '25th': np.percentile(array, 25, axis=0),
    '50th (Median)': np.percentile(array, 50, axis=0),
    '75th': np.percentile(array, 75, axis=0)
}
print("Percentiles for each column:")
print(percentiles_columns)

percentiles_rows = {
    '25th': np.percentile(array, 25, axis=1),
    '50th (Median)': np.percentile(array, 50, axis=1),
    '75th': np.percentile(array, 75, axis=1)
}
print("Percentiles for each row:")
print(percentiles_rows)

# (iii) Mean, Median, and Standard Deviation
mean_flattened = np.mean(flattened_array)
median_flattened = np.median(flattened_array)
std_dev_flattened = np.std(flattened_array)

print("Flattened array statistics:")
print(f"Mean: {mean_flattened}")
print(f"Median: {median_flattened}")
print(f"Standard Deviation: {std_dev_flattened}")

mean_columns = np.mean(array, axis=0)
median_columns = np.median(array, axis=0)
std_dev_columns = np.std(array, axis=0)

print("Statistics for each column:")
print(f"Mean: {mean_columns}")
print(f"Median: {median_columns}")
print(f"Standard Deviation: {std_dev_columns}")

mean_rows = np.mean(array, axis=1)
median_rows = np.median(array, axis=1)
std_dev_rows = np.std(array, axis=1)

print("Statistics for each row:")
print(f"Mean: {mean_rows}")
print(f"Median: {median_rows}")
print(f"Standard Deviation: {std_dev_rows}")


Element-wise absolute value:
[[1 2 3]
 [4 5 6]]
Percentiles of flattened array:
{'25th': -3.5, '50th (Median)': -0.5, '75th': 2.5}
Percentiles for each column:
{'25th': array([-2.75, -0.25, -3.75]), '50th (Median)': array([-1.5,  1.5, -1.5]), '75th': array([-0.25,  3.25,  0.75])}
Percentiles for each row:
{'25th': array([-0.5, -5. ]), '50th (Median)': array([ 1., -4.]), '75th': array([2. , 0.5])}
Flattened array statistics:
Mean: -0.5
Median: -0.5
Standard Deviation: 3.8622100754188224
Statistics for each column:
Mean: [-1.5  1.5 -1.5]
Median: [-1.5  1.5 -1.5]
Standard Deviation: [2.5 3.5 4.5]
Statistics for each row:
Mean: [ 0.66666667 -1.66666667]
Median: [ 1. -4.]
Standard Deviation: [2.05480467 4.78423336]


(b) For the array: a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0]). Find floor, ceiling
and truncated value, rounded values

In [ ]:
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])

# Floor values
floor_values = np.floor(a)
print("Floor values:")
print(floor_values)

# Ceiling values
ceiling_values = np.ceil(a)
print("Ceiling values:")
print(ceiling_values)

# Truncated values
truncated_values = np.trunc(a)
print("Truncated values:")
print(truncated_values)

# Rounded values
rounded_values = np.round(a)
print("Rounded values:")
print(rounded_values)

Floor values:
[-2. -2. -1.  0.  1.  1.  3.]
Ceiling values:
[-1. -1. -0.  1.  2.  2.  3.]
Truncated values:
[-1. -1. -0.  0.  1.  1.  3.]
Rounded values:
[-2. -2. -0.  0.  2.  2.  3.]


## Q3: Based on Searching and Sorting
(a) For the array: array = np.array([10, 52, 62, 16, 16, 54, 453]), find
i. Sorted array
ii. Indices of sorted array
iii. 4 smallest elements
iv. 5 largest elements
(b) For the array: array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0]), find
i. Integer elements only
ii. Float elements only

In [ ]:
array = np.array([10, 52, 62, 16, 16, 54, 453])

# (i) Sorted array
sorted_array = np.sort(array)
print("Sorted array:")
print(sorted_array)

# (ii) Indices of sorted array
sorted_indices = np.argsort(array)
print("Indices of sorted array:")
print(sorted_indices)

# (iii) 4 smallest elements
four_smallest = sorted_array[:4]
print("4 smallest elements:")
print(four_smallest)

# (iv) 5 largest elements
five_largest = sorted_array[-5:]
print("5 largest elements:")
print(five_largest)

Sorted array:
[ 10  16  16  52  54  62 453]
Indices of sorted array:
[0 3 4 1 5 2 6]
4 smallest elements:
[10 16 16 52]
5 largest elements:
[ 16  52  54  62 453]


In [ ]:
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])

# (i) Integer elements only
integer_elements = array[array == array.astype(int)]
print("Integer elements only:")
print(integer_elements)

# (ii) Float elements only
float_elements = array[array != array.astype(int)]
print("Float elements only:")
print(float_elements)

Integer elements only:
[1. 2. 3. 2.]
Float elements only:
[1.2 2.2]


Q4:
(a) Write a function named img_to_array(path) that reads an image from a specified path and
save it as text file on local machine? (Note: use separate cases for RGB and Grey Scale
images)


In [ ]:
from PIL import Image
import numpy as np

def img_to_array(path):


    img = Image.open(path)


    img_array = np.array(img)

    if len(img_array.shape) == 2:

        image_type = 'Grayscale'
    elif len(img_array.shape) == 3 and img_array.shape[2] == 3:

        image_type = 'RGB'
    else:
        raise ValueError("Unsupported image format")
    print(image_type)

    text_filename = path.rsplit('.', 1)[0] + '_array.txt'

    with open(text_filename, 'w') as f:
        if image_type == 'Grayscale':

            np.savetxt(f, img_array, fmt='%d')
        elif image_type == 'RGB':

            img_array_flat = img_array.reshape(-1, img_array.shape[2])
            np.savetxt(f, img_array_flat, fmt='%d', delimiter=',')

    print(f"Array saved to {text_filename}")

path = r'/content/8-bit City_1920x1080.jpg'


img_to_array(path)


(1080, 1920, 3)
RGB
Array saved to /content/8-bit City_1920x1080_array.txt
